include: package:lints/recommended.yaml

analyzer:
  exclude:
    -  test/**

linter:
  rules:
    - close_sinks
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - comment_references
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - use_super_parameters
    - prefer_single_quotes
    - always_declare_return_types
    - cancel_subscriptions
    - combinators_ordering
    - comment_references
    - dangling_library_doc_comments
    - collection_methods_unrelated_type
    - invalid_case_patterns
    - implicit_call_tearoffs: true
