name: rubik_utils
description: RubikUtils is a collection of utilities for project Flutter.

version: 1.0.2

homepage: https://github.com/cubos/cubos_extensions

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.19.0
  string_validator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^3.0.0