name: rubik_utils
description: RubikUtils is a collection of utilities for project Flutter.

version: 1.0.0

homepage: https://git.cubos.io/cubos/flutter-packages/rubik_utils

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.18.0
  string_validator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dart_code_metrics: ^5.6.0