name: cubos_extensions
description: Flutter package containing the most used extension functions in Cubos Tecnologia's projects.
version: 1.4.0
homepage: https://github.com/daniloapr/cubos_extensions

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
